"""Bundle Safari's single preprocessing script without a runtime network dependency."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def bundle() -> str:
    vendor = (ROOT / "scripts/vendor/readability/Readability.js").read_text()
    capture = (ROOT / "scripts/safari_capture.js").read_text()
    helpers = (ROOT / "scripts/capture_helpers.js").read_text()
    return (
        "// Generated by scripts/build_safari_capture.py. Do not edit.\n"
        + vendor
        + "\n"
        + helpers
        + "\n"
        + capture
    )


if __name__ == "__main__":
    (ROOT / "ios/HearfulShare/CapturePage.js").write_text(bundle())
